--- 
title: "Proyecto DataViz"
author: "Jorge Arteaga y Adriana Palacio"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
cover-image: Images/cover.jfif
description: |
  Ese libro contiene el detalle del proyecto enfocado a sistemas de información geográfica.
link-citations: yes
github-repo: rstudio/bookdown-demo
always_allow_html: true
---

# Sobre este libro

Este libro contiene el detalle del proyecto enfocado a sistemas de información geográfica. Se estará trabajando con un archivo tomado de *Kaggle* en <https://www.kaggle.com/dgomonov/data-exploration-on-nyc-airbnb> que contiene información resumida y métricas para Airbnb en la ciudad de Nueva York en 2019.

##  Objetivos

Este documento pretente encontrar como están distribuidos los precios de los airbnb en Nueva York. Haciendo un análisis por anfitrión, por tipo de alojamiento y por grupo de vecindario. Para lograr esto, realizaremos:

- Un análisis preliminar de los datos.
- Un análisis de datos faltantes y atípicos que puedan entorpecer las conclusiones.
- Un análisis por distribución geográfica.
 
Con estos resultados se construirá una aplicación en `Shiny`.

## Paquetes Necesarios

Para poder trabajar con estos datos se hace necesario cargar una serie de librerías.

1. Para el cargue del archivo csv, utilizaremos el paquete `readr`.
2. Para el manejo de dataframe, utilizaremos el paquete `dplyr`.
3. Para revisión de datos faltantes, utilizaremos los paquetes `mice` y `VIM`.
4. Para conexión a la base de datos PostgreSQL, utilizaremos el paquete `RPostgresL`.
5. Para poder hacer uso de la API y realizar la conexión a la base de datos con éxito, utilizaremos el paquete `DBI`.
6. Para poder identificar datos atípicos, utilizaremos los paquetes `outliers` y `EnvStats`.
7 Para graficar, utilizararemos el paquete `ggplot2`.
8. Para generar gráficos dinámicos, utilizaremos el paquete `plotly`.
9. Para visualización en mapas, utilizaremos el paquete `ggmap`.
10. Para la construcción de la aplicación, utilizaremos los paquetes `shiny` y `shinythemes`. 


```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(mice)
library(VIM)
library(RPostgres)
library(DBI)
library(outliers)
library(EnvStats)
library(ggplot2)
library(plotly)
library(ggmap)
library(shiny)
library(shinythemes)
```

